### ISSUE TITLE
JSON is all uppercase

### ISSUE THREAD

**Issue by ylupien** [schdck/create-env-json#2]
Hi !

Look like I have an case issue with this github action. I specified lower case in the configuration and the generated file is in uppercase.

```
      - name: Write hg-version.json
        uses: schdck/create-env-json@v2
        id: create-env
        with:
          file-name: './public/hg-version.json'
          version: ${{ github.sha }}
          test: '123'
```

```
{"VERSION":"695927bb3fa6176ae36ccb2216aa53dc85b5b542","TEST":"123"}
```

Any recommendation ?

**Comment by SouthernYoda** [comment]
I encountered the same issue. 

@ylupien have you managed to find a resolution for this?

**Comment by schdck** [comment]
Hey @ylupien @SouthernYoda, sorry for the delay. I've taken a quick look into the code but haven't managed to identify what's causing this behavior. Fixing this would require some debugging, which I don't currently have the time to do. I'll take a look into it as soon as I can, but in the mean time, feel free to take a look and submit a PR if you guys find anything

**Comment by SouthernYoda** [comment]
This appears to be a limitation of using GitHub inputs in this way, the input keys are automatically converted to uppercase as described in the documentation for GitHub inputs. It's too bad because I really like how you specified the inputs.

"When you specify an input to an action in a workflow file or use a default input value, GitHub creates an environment variable for the input with the name INPUT_<VARIABLE_NAME>. The environment variable created converts input names to uppercase letters and replaces spaces with _ characters." (https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs)

I've forked your repo and printed the "key" variable to console. The key value is already uppercase when it is read by the script.
![image](https://user-images.githubusercontent.com/15722886/91442972-a874cf80-e840-11ea-95c4-c69463a07878.png)

A resolution might be to nest the input so the user enters in:
```
<arbitrary element name>: 
  key: <desired key>
  value: <value>
<arbitrary element name>:
  key: <desired key>
  value: <value>
```

Hope this helped, I don't have experience with node so this is as much help as I can provide for now.

**Comment by dotKuro** [comment]
What about?:
```yaml
json-content:
  - key: foo
    value: blub
  - key: bar
    value: buz
```

This would eliminate the unnecessary name for each element.
